# Production environment overrides

replicaCount: 3

image:
  tag: "1.27-alpine"

ingress:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
