# Dev environment overrides

replicaCount: 1

image:
  tag: latest

ingress:
  enabled: true
  host: demo.dev.example.com

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
