# Dev environment overrides

vault:
  server:
    dev:
      enabled: true
      devRootToken: "root"

    standalone:
      enabled: true

    replicas: 1

    dataStorage:
      enabled: true
      size: 1Gi

    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  injector:
    enabled: true
